CONTIKI_PROJECT = tester tx_node
all: $(CONTIKI_PROJECT)

CONTIKI = ../../contiki-ng

PLATFORMS_ONLY = simplelink

MAKE_MAC ?= MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include
