#!/bin/sh
GLOSSY_DIR := ../..

# PROJECTDIRS += $(GLOSSY_DIR)/arch/platform/cc26x0-cc13x0/sensortag/cc1350
# PROJECTDIRS += $(GLOSSY_DIR)/core/net

CONTIKI_PROJECT = glossy_scratch
all: $(CONTIKI_PROJECT)
CONTIKI = $(GLOSSY_DIR)/contiki-ng
include $(CONTIKI)/Makefile.include
