GLOSSY_DIR := ../..

PLATFORMS_ONLY = simplelink
#PLATFORMS_ONLY = cc26x0-cc13x0

CONTIKI_PROJECT = address_finder 
all: $(CONTIKI_PROJECT)
CONTIKI = $(GLOSSY_DIR)/contiki-ng
include $(CONTIKI)/Makefile.include
